### ISSUE TITLE
Corporation application buttons are varying sizes / inconsistent locations

### ISSUE THREAD

**Issue by bearthatcares** [minmatarfleet/minmatar.org#158]
![chrome_hkTGmboKQw](https://github.com/minmatarfleet/minmatar.org/assets/149488155/ec2e7b1a-bec1-463e-b8f3-ffd021cbb01a)
![chrome_1eOo8iwIWk](https://github.com/minmatarfleet/minmatar.org/assets/149488155/84d89bbf-3619-463a-8ffd-619050f781b0)

I noticed that the buttons were varying sizes and the small ones are a little bit harder to read. Joined is also the same color as submit.

**Comment by beautifulmim** [comment]
Improved at #211

**Comment by bearthatcares** [comment]
@beautifulmim still have this issue for osme reason
