### ISSUE TITLE
Update frontend flow for primary characters

### ISSUE THREAD

**Issue by bearthatcares** [minmatarfleet/minmatar.org#213]
i made a new endpoint
PUT characters/primary
this is how we shouldset primary characters from now on
instead of adding a token for them / replacing the existing token
it's problematic because when you add a new token it replaces the old one
and we need to have CEO tokens
but CEOs are often mains
so that flow is just fucked 
but new endpoint will fix this
https://api.minmatar.org/api/docs#/Characters/eveonline_routers_characters_set_primary_character
use this instead of https://api.minmatar.org/api/docs#/Characters/eveonline_routers_characters_add_primary_character pls
<3
i have a lot of tickets to do for actual work today
but i want to get a lot of the notification logic in

**Comment by beautifulmim** [comment]
Implemented with #214
