### ISSUE TITLE
Need a way to add CEO tokens for corporations that are missing them

### ISSUE THREAD

**Issue by bearthatcares** [minmatarfleet/minmatar.org#253]
Endpoint: `https://api.minmatar.org/api/eveonline/characters/add?redirect_url=https%3A%2F%2Fapi.minmatar.org%2F&token_type=CEO`

We need all corporations for alliance / associates to have CEO tokens associated with them. Needs to be some sort of place where we make sure they add tokens for these

Example
![chrome_UCjkCD9qAq](https://github.com/minmatarfleet/minmatar.org/assets/149488155/c4160437-8998-4d7c-b7d1-4fa7e1d6a7e9)

**Comment by beautifulmim** [comment]
Implemented with #260 #261 #262 #263
