### ISSUE TITLE
Error 500 on Update Fleet Srp endpoint

### ISSUE THREAD

**Issue by beautifulmim** [minmatarfleet/minmatar.org#942]
Endpoint `PATCH /api/srp/{reimbursement_id}` is returning 500 with the following error `Unexpected token '<', "` despite of successfully patch the item

**Comment by silvatek** [comment]
Could this be another case of the response being an html error page rather than JSON @beautifulmim ?

**Comment by silvatek** [comment]
This could be due to an error sending the EveMail after updating the SRP status.

https://minmatar-fleet.sentry.io/issues/6102472491/?project=4507074556329984&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D%20%2Fapi%2Fsrp&referrer=issue-stream&statsPeriod=24h&stream_index=0

**Comment by beautifulmim** [comment]
Fixed on https://github.com/minmatarfleet/minmatar.org/pull/943/commits/9bf50eb8c9e9a119db66aaecd4bbe9749c84e201
